### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Litefallen** [Litefallen/spotify_edit#1]
- [x] selecting playlist
- [x] removing tracks from the playlist
- [ ] sometimes you need to press 'try again' on a web page after confirming access to spotify permissions
- [x] errorchecks
- [ ] artist/song search in user library
- [ ] download music?
- [ ] something else
